### ISSUE TITLE
Error in aiohttp_client_cache on Linux

### ISSUE THREAD

**Issue by bmolenaar** [JWCook/aiohttp-client-cache#71]
### The problem
The following error is thrown when trying to run my application on Linux. The application runs fine in Windows

>  Traceback (most recent call last):
>    File "dex.py", line 32, in <module>
>      from aiohttp_client_cache import CachedSession, SQLiteBackend
>    File "/home/ben/.local/lib/python3.6/site-packages/aiohttp_client_cache/__init__.py", line 5, in <module>
>      from aiohttp_client_cache.backends import *
>    File "/home/ben/.local/lib/python3.6/site-packages/aiohttp_client_cache/backends/__init__.py", line 5, in <module>
>      from aiohttp_client_cache.backends.base import (  # noqa: F401
>    File "/home/ben/.local/lib/python3.6/site-packages/aiohttp_client_cache/backends/base.py", line 14, in <module>
>      from aiohttp_client_cache.response import AnyResponse, CachedResponse
>    File "/home/ben/.local/lib/python3.6/site-packages/aiohttp_client_cache/response.py", line 38, in <module>
>      LinkMultiDict = MultiDictProxy[MultiDictProxy[Union[str, URL]]]
>  TypeError: 'type' object is not subscriptable

### Expected behavior
Behaviour is consistent with Windows environment

### Steps to reproduce the behavior
Try running the following code in Ubuntu Linux:
```
#import gevent
#from gevent import monkey
#monkey.patch_all(thread=False)
#import grequests
import json
import kivy
from kivy.app import App
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.gridlayout import GridLayout
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.base import runTouchApp
from kivy.uix.button import Button
from kivy.uix.behaviors import ButtonBehavior
from kivy.uix.label import Label
from kivy.uix.image import AsyncImage
from kivy.core.window import Window
from kivy.uix.scrollview import ScrollView
from kivy.clock import Clock
from kivy.network.urlrequest import UrlRequest
Clock.max_iteration = 152
from kivy.animation import Animation
import time
import certifi
import os
import threading
from functools import partial
import aiohttp
import asyncio
#import requests_cache
from aiohttp_client_cache import CachedSession, SQLiteBackend

BASE_URL = "https://pokeapi.co/api/v2/pokemon/"
NUM_POKES = 152
os.environ['SSL_CERT_FILE'] = certifi.where()
requests_cache.install_cache('poke_cache', backend='sqlite')
start_time = time.time()

def exception_handler(r, e):
	print('failed ', r.url, '\n')
	res = r.send().response
	return res

async def query_api(urls):
	now = time.ctime(int(time.time()))
	result = []
	#async with aiohttp.ClientSession() as session:
	async with CachedSession(cache=SQLiteBackend('poke_cache')) as session:
		for u in urls:
			async with session.get(u) as resp:
				pokemon = await resp.json()
				result.append(pokemon)

	print("--- %s seconds ---" % (time.time() - start_time))
	return(result)


def success(result, lst, *args):
	result.append(lst.result)

def failure(req, result):
	print(result.resp_status)

def make_list():
	urls  = []
	for p in range(NUM_POKES):
		if p != 0:
			url = '{0}{1}'.format(BASE_URL, str(p))
			urls.append(url)
	return urls


def get_pokemon_id(data):
	pokeId = data
	if pokeId  < 10:
		pokeId = '{0}{1}'.format('00',str(pokeId))
	elif pokeId > 9 and pokeId < 100:
		pokeId = str(0) + str(pokeId)
		
	return str(pokeId)

def get_pokemon_types(data):
	allTypes = data
	types = []
	
	for r in allTypes:
		types.append(r['type']['name'])
	
	if len(types) < 2:
		pokeType = types[0]
	else:
		pokeType = str(types[0] + "/" + types[1])
	
	return pokeType

def get_pokemon_abilities(data):
	allAbilities = data
	abilities  = []
				
	for a in allAbilities:
		abilities.append(a['ability']['name'])
	
	if len(abilities) == 1:
		pokeAbility =  abilities[0]
	elif len(abilities) == 2:
		pokeAbility = (abilities[0] + "/" + abilities[1])
	else:
		pokeAbility = (abilities[0] + "/" + abilities[1] + "/" + abilities[2])
	
	return pokeAbility


def return_pokemon(self):
	pokes = []
	for i in range(NUM_POKES):
		if i != 0:
			pokes.append(i)
		
	return pokes
    

class MenuScreen(Screen):
    Builder.load_string("""
<MenuScreen>:
    BoxLayout:
        Button:
            text: 'Go to dex'
            on_press: root.manager.current = 'Title'
        Button:
            text: 'Quit'
		""")

sm =  ScreenManager()
sm.add_widget(MenuScreen())

class MyGrid(Screen):
	
	def __init__(self, **kwargs):
		
		super(MyGrid, self).__init__(**kwargs)
		self.name = 'Title'
		t1 = threading.Thread(target=self.loading)
		t2 = threading.Thread(target=self.doAll)
		t1.start()
		t2.start()
		t1.join()

		
	def loading(self, **args):
		
		self.lbl = Label(text='loading')
		self.add_widget(self.lbl)
		
	
	def doAll(self, **args):
		
		self.scroller = ScrollView()
		
		self.outside = FloatLayout()
		self.outside.size_hint_y = 30
		
		self.add_widget(self.scroller)
		self.scroller.add_widget(self.outside)
		
		self.inside = GridLayout()
		self.inside.cols = 2
		self.outside.add_widget(self.inside)
		
		self.inner  = GridLayout()
		self.inner.cols = 2
		self.outside.add_widget(self.inner)
		
		urls = make_list()
		pokemon = asyncio.run(query_api(urls))
		
		
		for p in pokemon:
			if p is not None:
				#time.sleep(0.05)
				#data = json.loads(p)
				data = p
				
				self.pokegrid  = GridLayout()
				self.pokegrid.cols = 2
				self.pokegrid.size_hint = (1.9, 1.9)
				
				self.inside.add_widget(Button(size_hint=(0.3,0.3), background_color=(51,23,186,1)))
				self.inside.add_widget(Button(background_color=(255,0,0,1)))
				
				toSplit = str(data['sprites']['other']['official-artwork'])
				start = toSplit.index(':') + 3
				end = toSplit.index('.png') + 4
				path = str(toSplit[start:end])

				self.inner.add_widget(AsyncImage(source=str(path), size_hint_x=0.5))
				self.inner.add_widget(self.pokegrid)
				
				self.pokegrid.add_widget(Label(font_size=30, text=str(get_pokemon_id(data['id']))))
				self.pokegrid.add_widget(Label(font_size=50, text=str(data['name'])))											
				self.pokegrid.add_widget(Label(font_size=30, text=str(get_pokemon_types(data['types']))))
				self.pokegrid.add_widget(Label(font_size=30, text=str(get_pokemon_abilities(data['abilities']))))
		
		self.remove_widget(self.lbl)

sm.add_widget(MyGrid())

class MyMainApp(App):
	def build(self):
		return (sm)
		#return(MyGrid())

if __name__ == "__main__":
	MyMainApp().run()
```

### Workarounds
_Is there an existing workaround for this issue?_
Works in Windows, but trying to build to Android through Linux

### Environment
- aiohttp-client-cache version: `0.4.0`
- Python version: `3.6.9`
- Platform: Ubuntu 18.04.5

**Comment by bmolenaar** [comment]
sorry, I just read aiohttp-client-cache has a requirement of python 3.7+.. I can't believe I missed that before.

**Comment by JWCook** [comment]
@bmolenaar No problem! Glad it was an easy fix at least.
